name: 'API Protector Diff Action'
description: 'Compares two API specification files (JSON/YAML) and reports differences and compatibility.'
author: 'API-PROTECTOR'

inputs:
  old-spec-file:
    description: 'Path to the old API specification file (YAML or JSON).'
    required: true
  new-spec-file:
    description: 'Path to the new API specification file (YAML or JSON).'
    required: true
  output-file:
    description: 'Optional path to write the diff output.'
    required: false

# outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.old-spec-file }}
    - ${{ inputs.new-spec-file }}
    - ${{ inputs.output-file && '-o' }}
    - ${{ inputs.output-file && inputs.output-file }}

branding:
  icon: 'shield' # Choose an icon from Feather icons (https://feathericons.com/)
  color: 'blue'  # Choose a color (e.g., yellow, blue, green, etc.)