name: API Compatibility Check

on: [push]

jobs:
  build-and-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          secrets: |
            "github_user=${{ secrets.GH_PACKAGES_USER }}" 
            "github_pat=${{ secrets.GH_PACKAGES_PAT }}"   
            
      - name: Run API Protector Diff
        uses: ./
        with:
          old-spec-file: ./swagger_2025-03-25.json
          new-spec-file: ./swagger_2025-03-26.json
          output-file: 'api-diff-output.txt' 

      - name: Upload diff artifact
        if: success() || failure() 
        uses: actions/upload-artifact@v4
        with:
          name: api-diff-report
          path: api-diff-output.txt