name: API Compatibility Check

on: [push]

jobs:
  build-and-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'maven'
          distribution: 'corretto'

      - name: Build project with Maven
        run: mvn -B package --file api-protector-cli/pom.xml 



      - name: Run API Protector Diff
        uses: ./
        with:
          old-spec-file: './swagger_2025-03-25.json' 
          new-spec-file: './swagger_2025-03-26.json'
          output-file: 'api-diff-output.txt' 

      - name: Upload diff artifact
        if: success() || failure() 
        uses: actions/upload-artifact@v4
        with:
          name: api-diff-report
          path: api-diff-output.txt