name: API Compatibility Check

on: [push]

jobs:
  build-and-diff:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run API Protector Diff
        uses: APIprotector/APIProtectorACTION
        with:
          old-spec-file: ./swagger_2025-03-25.json
          new-spec-file: ./swagger_2025-03-26.json 
          output_file_name: 'api-diff-output.txt'  
          gh_packages_user: ${{ secrets.GH_PACKAGES_USER }} 
          gh_packages_pat: ${{ secrets.GH_PACKAGES_PAT }}   

      - name: Upload diff artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-diff-report
          path: api-diff-output.txt