name: API Compatibility Check

on: [push]

jobs:
  build-and-diff:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setting up maven
        run: |
          sudo apt install maven
          mvn -v 



          # echo "  <settings> " >> ./settings.xml
          # echo "    <servers>" >> ./settings.xml
          # echo "      <server>" >> ./settings.xml
          # echo "        <id>github</id>" >> ./settings.xml
          # echo "        <username>${{ secrets.GH_PACKAGES_USER }}</username>" >> ./settings.xml
          # echo "        <password>${{ secrets.GH_PACKAGES_PAT }}</password>" >> ./settings.xml
          # echo "      </server>" >> ./settings.xml
          # echo "    </servers>" >> ./settings.xml
          # echo "  </settings>  " >> ./settings.xml

      - name: Create settings.xml file
        run: |
          touch settings.xml

          echo "  <settings>  " >> settings.xml
          echo "            <activeProfiles> " >> settings.xml
          echo "    <activeProfile>github</activeProfile> " >> settings.xml
          echo "  </activeProfiles> " >> settings.xml

          echo "     <profiles> " >> settings.xml
          echo "         <profile> " >> settings.xml
          echo "             <id>github</id> " >> settings.xml
          echo "             <repositories> " >> settings.xml
          echo "                 <repository> " >> settings.xml
          echo "                     <id>github</id> " >> settings.xml
          echo "                     <url>https://maven.pkg.github.com/apiprotector/API-Protector</url> " >> settings.xml
          echo "                     <snapshots> " >> settings.xml
          echo "                         <enabled>true</enabled> " >> settings.xml
          echo "                     </snapshots> " >> settings.xml
          echo "                 </repository> " >> settings.xml
          echo "             </repositories> " >> settings.xml
          echo "         </profile> " >> settings.xml
          echo "     </profiles> " >> settings.xml
          echo "     <servers> " >> settings.xml
          echo "         <server> " >> settings.xml
          echo "             <id>github</id> " >> settings.xml
          echo "             <username>${{ secrets.GH_PACKAGES_USER }}</username> " >> settings.xml
          echo "             <password>${{ secrets.GH_PACKAGES_PAT }}</password> " >> settings.xml
          echo "         </server> " >> settings.xml
          echo "     </servers> " >> settings.xml
          echo " </settings> " >> settings.xml




          ls -al 

          mvn dependency:copy \
          -Dartifact=com.apiprotector:api-protector-cli:2.0.1-SNAPSHOT \
          -DoutputDirectory=. \
          -DrepositoryId=github \
          --settings ./settings.xml
      
      # - name: Download jar newest version
      #   run: |
      #     curl -O -L https://x-access-token:${{ secrets.GH_PACKAGES_PAT }}@maven.pkg.github.com/com/apiprotector/api-protector-cli/2.0.1-SNAPSHOT/api-protector-cli-2.0.1-SNAPSHOT.jar
      #     cat api-protector-cli-2.0.1-SNAPSHOT.jar
      # - name: Add permissions to jar
      #   run: |
      #     chmod 777 api-protector-cli-2.0.1-SNAPSHOT.jar

      - name: Run API Protector Diff
        uses: ./
        with:
          old-spec-file: ./swagger_2025-03-25.json
          new-spec-file: ./swagger_2025-03-26.json
          output-file: 'api-diff-output.txt' 

      - name: Upload diff artifact
        if: success() || failure() 
        uses: actions/upload-artifact@v4
        with:
          name: api-diff-report
          path: api-diff-output.txt